module.exports = Object.freeze({
  ENUM_GENDER: ['Female', 'Male', 'Prefer not to say', 'Other'],
  ENUM_NATIONALITY: [
    'Afghanistan',
    'Iran',
    'Iraq',
    'Syria',
    'Turkey',
    'Ukraine',
    'Other',
  ],
  ENUM_REPORT_STATUS: ['Pending', 'Resolved'],
  ENUM_PROVIDER: ['Local', 'Google', 'Facebook'],
  ENUM_CATEGORY: [
    'Books',
    'Clothing',
    'Electronics',
    'Food',
    'Furniture',
    'Kitchenware',
    'Linens',
    'Toys',
    'Other',
  ],
  ENUM_REQUEST_STATUS: ['Requested', 'Confirmed', 'Rejected'],
  ENUM_PRODUCT_CONDITION: ['New', 'Underused', 'Overused'],
  ENUM_SHIPPING_OPTION: [
    'Meet up',
    'Drop off',
    'Free shipping',
    'Paid shipping',
    'To be determined',
  ],
  ENUM_POST_TYPE: ['Request', 'Donate'],
  ENUM_POST_STATUS: ['Published', 'Verified'],
  PUBLIC_AUTH_ROUTES: [
    { method: 'get', path: '/api/auth/login' },
    { method: 'get', path: '/api/auth/register' },
    { method: 'get', path: '/api/auth/google' },
    { method: 'get', path: '/api/auth/google/callback' },
    { method: 'get', path: '/api/auth/facebook' },
    { method: 'get', path: '/api/auth/facebook/callback' },
  ],

  PUBLIC_ROUTES: [
    { method: 'get', path: '/api/' },
    { method: 'get', path: '/api/about' },
    { method: 'get', path: '/api/posts' },
    { method: 'get', path: '/api/posts' },
    { method: 'get', path: '/api/posts/?filter&&?search' },
    { method: 'get', path: '/api/post/:id' },
  ],
  PRIVATE_ROUTES: [
    { method: 'post', path: '/api/post' },
    { method: 'put', path: '/api/post/:id' },
    { method: 'delete', path: '/api/post/:id' },
    { method: 'get', path: '/api/auth/profile' },
    { method: 'get', path: '/api/auth/logout' },
  ],
});
